package com.prenda.model.dao;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.Branch;
 
/**
 * DAO interface for table: Branch.
 * @author autogenerated
 */
public interface BranchDao extends GenericDAO<Branch,  Byte>  {
	// constructor only
}

