package com.prenda.model.dao;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.Customer;
 
/**
 * DAO interface for table: Customer.
 * @author autogenerated
 */
public interface CustomerDao extends GenericDAO<Customer,  Long>  {
	// constructor only
}

