package com.prenda.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.Genkey;
 
/**
 * DAO interface for table: Genkey.
 * @author autogenerated
 */
public interface GenkeyDao extends GenericDAO<Genkey,  Long>  {
	// constructor only
}

