package com.prenda.model.dao;

import java.io.Serializable;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.Interest;
 
/**
 * DAO interface for table: Interest.
 * @author autogenerated
 */
public interface InterestDao extends GenericDAO<Interest,  Serializable>  {
	// constructor only
}

