package com.prenda.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.Level;
 
/**
 * DAO interface for table: Level.
 * @author autogenerated
 */
public interface LevelDao extends GenericDAO<Level,  Byte>  {
	// constructor only
}

