package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Branch;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.BranchDao;
 
 
/**
 * DAO for table: Branch.
 * @author autogenerated
 */
@Repository
public class BranchDaoImpl extends GenericHibernateDaoImpl<Branch, Integer> implements BranchDao {
	
	/** Constructor method. */
		public BranchDaoImpl() {
			super(Branch.class);
		}
	}

