package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Customer;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.CustomerDao;
 
 
/**
 * DAO for table: Customer.
 * @author autogenerated
 */
@Repository
public class CustomerDaoImpl extends GenericHibernateDaoImpl<Customer, Long> implements CustomerDao {
	
	/** Constructor method. */
		public CustomerDaoImpl() {
			super(Customer.class);
		}
	}

