package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Genkey;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.GenkeyDao;
 
 
/**
 * DAO for table: Genkey.
 * @author autogenerated
 */
@Repository
public class GenkeyDaoImpl extends GenericHibernateDaoImpl<Genkey, Long> implements GenkeyDao {
	
	/** Constructor method. */
		public GenkeyDaoImpl() {
			super(Genkey.class);
		}
	}

