package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Interest;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.InterestDao;
import com.prenda.model.obj.prenda.InterestPK;
 
/**
 * DAO for table: Interest.
 * @author autogenerated
 */
@Repository
public class InterestDaoImpl extends GenericHibernateDaoImpl<Interest, InterestPK> implements InterestDao {
	
	/** Constructor method. */
		public InterestDaoImpl() {
			super(Interest.class);
		}
	}

