package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Jewelry;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.JewelryDao;
import com.prenda.model.obj.prenda.JewelryPK;
 
/**
 * DAO for table: Jewelry.
 * @author autogenerated
 */
@Repository
public class JewelryDaoImpl extends GenericHibernateDaoImpl<Jewelry, JewelryPK> implements JewelryDao {
	
	/** Constructor method. */
		public JewelryDaoImpl() {
			super(Jewelry.class);
		}
	}

