package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.JewelryPK;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.JewelryPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: JewelryPK.
 * @author autogenerated
 */
@Repository
public class JewelryPKDaoImpl extends GenericHibernateDaoImpl<JewelryPK, Serializable> implements JewelryPKDao {
	
	/** Constructor method. */
		public JewelryPKDaoImpl() {
			super(JewelryPK.class);
		}
	}

