package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Journal;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.JournalDao;
 
 
/**
 * DAO for table: Journal.
 * @author autogenerated
 */
@Repository
public class JournalDaoImpl extends GenericHibernateDaoImpl<Journal, Long> implements JournalDao {
	
	/** Constructor method. */
		public JournalDaoImpl() {
			super(Journal.class);
		}
	}

