package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Limits;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.LimitsDao;
 
 
/**
 * DAO for table: Limits.
 * @author autogenerated
 */
@Repository
public class LimitsDaoImpl extends GenericHibernateDaoImpl<Limits, Integer> implements LimitsDao {
	
	/** Constructor method. */
		public LimitsDaoImpl() {
			super(Limits.class);
		}
	}

