package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Page;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.PageDao;
 
 
/**
 * DAO for table: Page.
 * @author autogenerated
 */
@Repository
public class PageDaoImpl extends GenericHibernateDaoImpl<Page, Integer> implements PageDao {
	
	/** Constructor method. */
		public PageDaoImpl() {
			super(Page.class);
		}
	}

