package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Pawn;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.PawnDao;
 
 
/**
 * DAO for table: Pawn.
 * @author autogenerated
 */
@Repository
public class PawnDaoImpl extends GenericHibernateDaoImpl<Pawn, Long> implements PawnDao {
	
	/** Constructor method. */
		public PawnDaoImpl() {
			super(Pawn.class);
		}
	}

