package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Pullout;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.PulloutDao;
 
 
/**
 * DAO for table: Pullout.
 * @author autogenerated
 */
@Repository
public class PulloutDaoImpl extends GenericHibernateDaoImpl<Pullout, Long> implements PulloutDao {
	
	/** Constructor method. */
		public PulloutDaoImpl() {
			super(Pullout.class);
		}
	}

