package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Redeem;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.RedeemDao;
 
 
/**
 * DAO for table: Redeem.
 * @author autogenerated
 */
@Repository
public class RedeemDaoImpl extends GenericHibernateDaoImpl<Redeem, Long> implements RedeemDao {
	
	/** Constructor method. */
		public RedeemDaoImpl() {
			super(Redeem.class);
		}
	}

