package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Register;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.RegisterDao;
 
 
/**
 * DAO for table: Register.
 * @author autogenerated
 */
@Repository
public class RegisterDaoImpl extends GenericHibernateDaoImpl<Register, Integer> implements RegisterDao {
	
	/** Constructor method. */
		public RegisterDaoImpl() {
			super(Register.class);
		}
	}

