package com.prenda.model.dao.prenda.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.prenda.Users;
import org.springframework.stereotype.Repository;
import com.prenda.model.dao.prenda.UsersDao;
 
 
/**
 * DAO for table: Users.
 * @author autogenerated
 */
@Repository
public class UsersDaoImpl extends GenericHibernateDaoImpl<Users, Integer> implements UsersDao {
	
	/** Constructor method. */
		public UsersDaoImpl() {
			super(Users.class);
		}
	}

