sjm.url=http://openshift.kenchlightyear.com
sjm.host=mail.kenchlightyear.com
sjm.port=587
sjm.user=joebertj@kenchlightyear.com
sjm.pass=Y@50uz3d
sjm.timeout=10
sjm.debug=false
sjm.from=Provisioning
sjm.fromEmail=joebertj@kenchlightyear.com
sjm.subject=Activate Prenda Account
sjm.postBody=Regards,<br/>Kenchlightyear Provisioning