package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.Branch;
 
/**
 * DAO interface for table: Branch.
 * @author autogenerated
 */
public interface BranchDao extends GenericDAO<Branch,  Integer>  {
	// constructor only
}

