package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.Interest;
import com.prenda.model.obj.prenda.InterestPK;
/**
 * DAO interface for table: Interest.
 * @author autogenerated
 */
public interface InterestDao extends GenericDAO<Interest,  InterestPK>  {
	// constructor only
}

