package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.InterestPK;
import java.io.Serializable;
/**
 * DAO interface for table: InterestPK.
 * @author autogenerated
 */
public interface InterestPKDao extends GenericDAO<InterestPK,  Serializable>  {
	// constructor only
}

