package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.Jewelry;
import com.prenda.model.obj.prenda.JewelryPK;
/**
 * DAO interface for table: Jewelry.
 * @author autogenerated
 */
public interface JewelryDao extends GenericDAO<Jewelry,  JewelryPK>  {
	// constructor only
}

