package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.JewelryPK;
import java.io.Serializable;
/**
 * DAO interface for table: JewelryPK.
 * @author autogenerated
 */
public interface JewelryPKDao extends GenericDAO<JewelryPK,  Serializable>  {
	// constructor only
}

