package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.Ledger;
 
/**
 * DAO interface for table: Ledger.
 * @author autogenerated
 */
public interface LedgerDao extends GenericDAO<Ledger,  Long>  {
	// constructor only
}

