package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.Level;
 
/**
 * DAO interface for table: Level.
 * @author autogenerated
 */
public interface LevelDao extends GenericDAO<Level,  Byte>  {
	// constructor only
}

