package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.Limits;
 
/**
 * DAO interface for table: Limits.
 * @author autogenerated
 */
public interface LimitsDao extends GenericDAO<Limits,  Integer>  {
	// constructor only
}

