package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.Page;
 
/**
 * DAO interface for table: Page.
 * @author autogenerated
 */
public interface PageDao extends GenericDAO<Page,  Integer>  {
	// constructor only
}

