package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.Pullout;
 
/**
 * DAO interface for table: Pullout.
 * @author autogenerated
 */
public interface PulloutDao extends GenericDAO<Pullout,  Long>  {
	// constructor only
}

