package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.Register;
 
/**
 * DAO interface for table: Register.
 * @author autogenerated
 */
public interface RegisterDao extends GenericDAO<Register,  Integer>  {
	// constructor only
}

