package com.prenda.model.dao.prenda;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.prenda.Users;
 
/**
 * DAO interface for table: Users.
 * @author autogenerated
 */
public interface UsersDao extends GenericDAO<Users,  Integer>  {
	// constructor only
}

