package com.prenda.factories.prenda;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.BeanNameAware;

import com.prenda.model.dao.prenda.*;

/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class HibernatePrendaDaoFactory implements ApplicationContextAware, BeanNameAware {
	/** Placeholder for an instance. */
	private static HibernatePrendaDaoFactory instance;
	/** Internal state. */
	private static ApplicationContext context = null;
	/** Bean Name. */
	private static String beanName;

	/** Return an instance of this class.
	 * @return an instance of this class
	 */
	public static synchronized HibernatePrendaDaoFactory getInstance() {
		if (instance == null) {
			instance = (HibernatePrendaDaoFactory) context.getBean(beanName);
		}
		return instance;
	}

	/**
	 * Sets a Spring Application Context object.
  	 * @param ctxt ApplicationContext to set
	 * @throws BeansException on spring error
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt)
			throws BeansException 
	{
		context = ctxt;
	}

	/**
	* 
	* {@inheritDoc}
	* 
	* @see org.springframework.beans.factory.BeanNameAware#setBeanName(java.lang.String)
	*/
	public void setBeanName(String name) {
		beanName = name;
	}

	/**
	 * Return the requested bean from the context, throwing a RuntimeException on error.
	 *
	 * @param beanName to return
	 * @return the bean requested.
	 */
	public static Object getBean(String beanName) {
		Object result = context.getBean(beanName);
		if (result == null) { 
			throw new IllegalStateException(String.format("Could not find bean '%s'. Did you set the right component scanning?", beanName));
		} 
		
		return result;
	}

	
	/**
	 * Returns a AccountsDao instance.
	 * 
	 * @return a AccountsDao instance
	 */
	public static AccountsDao getAccountsDao() {
		return (AccountsDao) getBean("accountsDaoImpl"); 
	}
	/**
	 * Returns a BranchDao instance.
	 * 
	 * @return a BranchDao instance
	 */
	public static BranchDao getBranchDao() {
		return (BranchDao) getBean("branchDaoImpl"); 
	}
	/**
	 * Returns a CustomerDao instance.
	 * 
	 * @return a CustomerDao instance
	 */
	public static CustomerDao getCustomerDao() {
		return (CustomerDao) getBean("customerDaoImpl"); 
	}
	/**
	 * Returns a GenkeyDao instance.
	 * 
	 * @return a GenkeyDao instance
	 */
	public static GenkeyDao getGenkeyDao() {
		return (GenkeyDao) getBean("genkeyDaoImpl"); 
	}
	/**
	 * Returns a InterestDao instance.
	 * 
	 * @return a InterestDao instance
	 */
	public static InterestDao getInterestDao() {
		return (InterestDao) getBean("interestDaoImpl"); 
	}
	/**
	 * Returns a JewelryDao instance.
	 * 
	 * @return a JewelryDao instance
	 */
	public static JewelryDao getJewelryDao() {
		return (JewelryDao) getBean("jewelryDaoImpl"); 
	}
	/**
	 * Returns a JournalDao instance.
	 * 
	 * @return a JournalDao instance
	 */
	public static JournalDao getJournalDao() {
		return (JournalDao) getBean("journalDaoImpl"); 
	}
	/**
	 * Returns a LedgerDao instance.
	 * 
	 * @return a LedgerDao instance
	 */
	public static LedgerDao getLedgerDao() {
		return (LedgerDao) getBean("ledgerDaoImpl"); 
	}
	/**
	 * Returns a LevelDao instance.
	 * 
	 * @return a LevelDao instance
	 */
	public static LevelDao getLevelDao() {
		return (LevelDao) getBean("levelDaoImpl"); 
	}
	/**
	 * Returns a PageDao instance.
	 * 
	 * @return a PageDao instance
	 */
	public static PageDao getPageDao() {
		return (PageDao) getBean("pageDaoImpl"); 
	}
	/**
	 * Returns a PawnDao instance.
	 * 
	 * @return a PawnDao instance
	 */
	public static PawnDao getPawnDao() {
		return (PawnDao) getBean("pawnDaoImpl"); 
	}
	/**
	 * Returns a PulloutDao instance.
	 * 
	 * @return a PulloutDao instance
	 */
	public static PulloutDao getPulloutDao() {
		return (PulloutDao) getBean("pulloutDaoImpl"); 
	}
	/**
	 * Returns a RedeemDao instance.
	 * 
	 * @return a RedeemDao instance
	 */
	public static RedeemDao getRedeemDao() {
		return (RedeemDao) getBean("redeemDaoImpl"); 
	}
	/**
	 * Returns a UsersDao instance.
	 * 
	 * @return a UsersDao instance
	 */
	public static UsersDao getUsersDao() {
		return (UsersDao) getBean("usersDaoImpl"); 
	}

}
