package com.prenda.model.dao.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.Accounts;

import org.springframework.stereotype.Repository;

import com.prenda.model.dao.AccountsDao;
 
 
/**
 * DAO for table: Accounts.
 * @author autogenerated
 */
@Repository
public class AccountsDaoImpl extends GenericHibernateDaoImpl<Accounts, Byte> implements AccountsDao {
	
	/** Constructor method. */
		public AccountsDaoImpl() {
			super(Accounts.class);
		}
	}

