package com.prenda.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.Ledger;

import org.springframework.stereotype.Repository;

import com.prenda.model.dao.LedgerDao;
 
 
/**
 * DAO for table: Ledger.
 * @author autogenerated
 */
@Repository
public class LedgerDaoImpl extends GenericHibernateDaoImpl<Ledger, Long> implements LedgerDao {
	
	/** Constructor method. */
		public LedgerDaoImpl() {
			super(Ledger.class);
		}
	}

