package com.prenda.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.Level;

import org.springframework.stereotype.Repository;

import com.prenda.model.dao.LevelDao;
 
 
/**
 * DAO for table: Level.
 * @author autogenerated
 */
@Repository
public class LevelDaoImpl extends GenericHibernateDaoImpl<Level, Byte> implements LevelDao {
	
	/** Constructor method. */
		public LevelDaoImpl() {
			super(Level.class);
		}
	}

