package com.prenda.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.Page;

import org.springframework.stereotype.Repository;

import com.prenda.model.dao.PageDao;
 
 
/**
 * DAO for table: Page.
 * @author autogenerated
 */
@Repository
public class PageDaoImpl extends GenericHibernateDaoImpl<Page, Long> implements PageDao {
	
	/** Constructor method. */
		public PageDaoImpl() {
			super(Page.class);
		}
	}

