package com.prenda.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.Pawn;

import org.springframework.stereotype.Repository;

import com.prenda.model.dao.PawnDao;
 
 
/**
 * DAO for table: Pawn.
 * @author autogenerated
 */
@Repository
public class PawnDaoImpl extends GenericHibernateDaoImpl<Pawn, Long> implements PawnDao {
	
	/** Constructor method. */
		public PawnDaoImpl() {
			super(Pawn.class);
		}
	}

