package com.prenda.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.Pullout;

import org.springframework.stereotype.Repository;

import com.prenda.model.dao.PulloutDao;
 
 
/**
 * DAO for table: Pullout.
 * @author autogenerated
 */
@Repository
public class PulloutDaoImpl extends GenericHibernateDaoImpl<Pullout, Long> implements PulloutDao {
	
	/** Constructor method. */
		public PulloutDaoImpl() {
			super(Pullout.class);
		}
	}

