package com.prenda.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.Redeem;

import org.springframework.stereotype.Repository;

import com.prenda.model.dao.RedeemDao;
 
 
/**
 * DAO for table: Redeem.
 * @author autogenerated
 */
@Repository
public class RedeemDaoImpl extends GenericHibernateDaoImpl<Redeem, Long> implements RedeemDao {
	
	/** Constructor method. */
		public RedeemDaoImpl() {
			super(Redeem.class);
		}
	}

