package com.prenda.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.Users;

import org.springframework.stereotype.Repository;

import com.prenda.model.dao.UsersDao;
 
 
/**
 * DAO for table: Users.
 * @author autogenerated
 */
@Repository
public class UsersDaoImpl extends GenericHibernateDaoImpl<Users, Byte> implements UsersDao {
	
	/** Constructor method. */
		public UsersDaoImpl() {
			super(Users.class);
		}
	}

