package com.prenda.model.dao;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.Accounts;
 
/**
 * DAO interface for table: Accounts.
 * @author autogenerated
 */
public interface AccountsDao extends GenericDAO<Accounts,  Byte>  {
	// constructor only
}

