package com.prenda.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.Journal;
 
/**
 * DAO interface for table: Journal.
 * @author autogenerated
 */
public interface JournalDao extends GenericDAO<Journal,  Long>  {
	// constructor only
}

