package com.prenda.model.dao;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.Page;
 
/**
 * DAO interface for table: Page.
 * @author autogenerated
 */
public interface PageDao extends GenericDAO<Page,  Long>  {
	// constructor only
}

