package com.prenda.model.dao;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.Pawn;
 
/**
 * DAO interface for table: Pawn.
 * @author autogenerated
 */
public interface PawnDao extends GenericDAO<Pawn,  Long>  {
	// constructor only
}

