package com.prenda.model.dao;

import com.github.wwadge.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.Redeem;
 
/**
 * DAO interface for table: Redeem.
 * @author autogenerated
 */
public interface RedeemDao extends GenericDAO<Redeem,  Long>  {
	// constructor only
}

