package com.prenda.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.prenda.model.obj.Users;
 
/**
 * DAO interface for table: Users.
 * @author autogenerated
 */
public interface UsersDao extends GenericDAO<Users,  Byte>  {
	// constructor only
}

