package com.prenda.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.Customer;

import org.springframework.stereotype.Repository;

import com.prenda.model.dao.CustomerDao;
 
 
/**
 * DAO for table: Customer.
 * @author autogenerated
 */
@Repository
public class CustomerDaoImpl extends GenericHibernateDaoImpl<Customer, Long> implements CustomerDao {
	
	/** Constructor method. */
		public CustomerDaoImpl() {
			super(Customer.class);
		}
	}

