package com.prenda.model.dao.impl;

import java.io.Serializable;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.Interest;

import org.springframework.stereotype.Repository;

import com.prenda.model.dao.InterestDao;
 
 
/**
 * DAO for table: Interest.
 * @author autogenerated
 */
@Repository
public class InterestDaoImpl extends GenericHibernateDaoImpl<Interest, Serializable> implements InterestDao {
	
	/** Constructor method. */
		public InterestDaoImpl() {
			super(Interest.class);
		}
	}

