package com.prenda.model.dao.impl;

import com.github.wwadge.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.prenda.model.obj.Journal;

import org.springframework.stereotype.Repository;

import com.prenda.model.dao.JournalDao;
 
 
/**
 * DAO for table: Journal.
 * @author autogenerated
 */
@Repository
public class JournalDaoImpl extends GenericHibernateDaoImpl<Journal, Long> implements JournalDao {
	
	/** Constructor method. */
		public JournalDaoImpl() {
			super(Journal.class);
		}
	}

